version: '3'
services:
    server:
        build:
            context: .
            dockerfile: Dockerfile_server
        container_name: server
        ports:
            - "3000:3000"
    keycloak:
        image: quay.io/keycloak/keycloak:23.0.4
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
        ports:
            - "8080:8080"
        command:
            - start-dev
        container_name: keycloak
    holder:
        build:
            context: .
            dockerfile: Dockerfile_holder
        container_name: holder
        ports:
            - "4000:4000"
            - "4001:4001"
    issuer:
        build:
            context: .
            dockerfile: Dockerfile_issuer
        container_name: issuer
        ports:
            - "5000:5000"
            - "5001:5001"
    verifier:
        build:
            context: .
            dockerfile: Dockerfile_verifier
        container_name: verifier
        ports:
            - "6000:6000"
            - "6001:6001"
