# Usa una imagen base con Node.js
FROM node:18.18

# Establece el directorio de trabajo en la aplicación
WORKDIR /usr/src/app

# Copia el archivo package.json e package-lock.json (si existen)
COPY IdentityProvider .

# Instala las dependencias
RUN npm install

# Expone el puerto en el que el servidor estará escuchando
EXPOSE 4000 4001 4002 4003

# Comando para ejecutar la aplicación
CMD ["npm", "start"]
